### ISSUE TITLE
Initialization always failing 

### ISSUE THREAD

**Issue by MoeyadDeere** [vChavezB/SimpleJ1939#1]
The code I am using is the exact same as the receive code my issue is the initialization is always failing I am using https://copperhilltech.com/esp32-wifi-bluetooth-classic-ble-can-bus-module/ which is a can bus on an esp 32 I know that my connections are right I have power and ground on the bus at 12V and gnd, I connected my can H and can L to a module which emulates my machine(I do not need the parallel resistors with the can Bus) I know my Can bus rate is 250k, I know my chip select pin is 5(I found code that tells you the chip select pin) I just can not figure out why it does not initialize the function keeps returning 1 not 0, I would really appreciate if some one could help me with this

**Comment by vChavezB** [comment]
Hello @MoeyadDeere ,

I dont think this library will work with your hardware.

According to the schematic of your board

https://copperhilltech.com/content/ESP32_CAN_rev_B.pdf

, the CAN Transciever is a MCP2562. This transciever does not have an SPI interface but rather directly uses the CAN transciever from the ESP32. 


![grafik](https://github.com/vChavezB/SimpleJ1939/assets/47216966/5a32563a-9e17-4fe1-a8b2-fb04799147ad)
